version: "3"

services:
    grpc: # GRPC SERVER + STORAGE
        env_file: .env
        build: 
            context: ./
            dockerfile: ./cmd/grpc/Dockerfile
        depends_on:
            # - redis 
            # - postgres
            - mongo
    server: # HTTP SERVER
        env_file: .env
        build: 
            context: ./
            dockerfile: ./cmd/http/Dockerfile
        ports: 
            - "${SERVER_PORT}:${SERVER_PORT}"
    # redis: # REDIS STORAGE FOR GRPC
    #     env_file: .env
    #     image: "redis:alpine"
    #     command:
    #         "redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}"
    #     ports: 
    #         - "${REDIS_PORT}:${REDIS_PORT}"
    # postgres:
    #     image: "postgres:alpine"
    #     environment: 
    #         POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    #         POSTGRES_USER: "${POSTGRES_USER}"
    #         PGPORT: "${POSTGRES_PORT}"
    #     volumes: 
    #         - "${PWD}/base/postgres:/var/lib/postgresql/data"
    mongo:
        image: "mongo"
        environment: 
            MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
        command: "mongod --port ${MONGO_PORT}"
    